### ISSUE TITLE
Add a new project template for expo

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir#146]
The new project template should:
 - create a new barebone expo project
 - have the tweaks to the tsconfig, babel.config.ts and metro.config.ts necessary to support bonfhir in expo
 - have a minimal configuration for the `@bonfhir/gluestack-ui` package created in #145 
 - proper prettier and eslint configuration working OOB

It should follow the existing conventions for other project templates

**Comment by julienblin** [comment]
Project templates are in the `cli` package, under the `template` folder, executed using the `create` command.

To test locally, the best is probably to `build` the `cli` package, and then from another folder in your local machine you can just execute the bundled version directly using node (without having to install the package):

e.g.

```bash
node <path to the bonFHIR monorepo>/bonfhir/bonfhir/packages/cli/dist/cli/index.cjs create
```

**Comment by julienblin** [comment]
This one has a dependency on #145 so I suggest working on #145 first.

**Comment by nickvallee** [comment]
@julienblin I think I am quite close to solving both this issue and #145. I ended up adding an expo project to the monorepo, because I discovered that sim linking required configuration in the `metro.config.ts` and once my first attempt at sim linking was unable to find package exports correctly, I thought my time would better be used to trouble shoot adding an expo package to the monorepo instead, since we would have to do it anyway. 

both the gluestack-ui package and the expo project can be found on [https://github.com/bonfhir/bonfhir/tree/145-create-a-bonfhirgluestack-ui-package](https://github.com/bonfhir/bonfhir/tree/145-create-a-bonfhirgluestack-ui-package)

If you have time to review these changes, please do so and let me know your thoughts. I have had some support from Ysael already, but we were not yet able to resolve it.

## Current Error: 

```
error: Error: While resolving module `@bonfhir/react/r4b`, the Haste package `@bonfhir/react` was found. However the module `r4b` could not be found within the package. Indeed, none of these files exist:

  * `/Users/nicolaasvallee/Projects/bonfhir/packages/react/r4b(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.mjs|.native.mjs|.mjs)`
  * `/Users/nicolaasvallee/Projects/bonfhir/packages/react/r4b/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.mjs|.native.mjs|.mjs)`
    at resolveHasteName (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro-resolver@0.76.8/node_modules/metro-resolver/src/resolve.js:218:9)
    at Object.resolve (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro-resolver@0.76.8/node_modules/metro-resolver/src/resolve.js:92:20)
    at ModuleResolver.resolveDependency (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:79:31)
    at DependencyGraph.resolveDependency (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 2)
    at async Graph._processModule (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
    at async Promise.all (index 0)
    at async Graph.initialTraverseDependencies (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/DeltaBundler/Graph.js:233:5)
    at async DeltaCalculator._getChangedDependencies (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:229:25)
    at async DeltaCalculator.getDelta (/Users/nicolaasvallee/Projects/bonfhir/node_modules/.pnpm/metro@0.76.8/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:112:16)
```

<img width="453" alt="Screenshot 2023-12-20 at 4 03 10 PM" src="https://github.com/bonfhir/bonfhir/assets/8885263/945854e1-ca6c-45bd-9053-f4f68f5e3d77">

As of now, the expo app is finding the package in the repo, but is unable to locate r4b. This works when importing the published bonfhir packages into an external expo app (given the correct configuration in the app). 

Things to consider when troubleshooting this issue: 
- adding an expo app into a monorepo using pnpm requires different configuration than normal. (There are different solutions in this thread)[https://github.com/expo/expo/issues/18038]
- One of the solutions above suggested adding a `.npmrc`. not certain it's needed or not. Need to look more in what it does to be sure.
- As far as I understand, simlinking seems important in a monorepo, and has [beta support](https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks)
- The doc instructions on using a monorepo with expo didn't seem to fit our case exactly, but [here they are](https://docs.expo.dev/guides/monorepos/)
- `metro.config.ts` is central to making all this work
- none of the bonfhir packages (react, core, query) and being react correctly.
- here is an example are a couple examples of Expo apps in mono repos:

[create-t3-turbo](https://github.com/t3-oss/create-t3-turbo/tree/main/apps/expo)
[expo-monorepo-example](https://github.com/byCedric/expo-monorepo-example/tree/main)

@ysael if you have anything to add please share!

Note: there may be some unnecessary code. just trying to get it to work at the moment

**Comment by julienblin** [comment]
@nickvallee - I won't accept a PR to add an expo app in the monorepo yet - As I told you, I know from experience the amount of problems it introduces both for the expo app, and the rest of the monorepo as well.
Please focus on submitting a PR for #145 first, and have it accepted.

**Comment by nickvallee** [comment]
@julienblin now that we have merged #145, I spent a bit of time re-testing the app in the monorepo, and also searching for some sort of solution. As of now I am stumped. It seems to locate the packages using `workspace:*`, but it then cannot detect the package exports.

I created a new branch with the current code here: https://github.com/bonfhir/bonfhir/tree/146-add-a-new-project-template-for-expo

Please lend any wisdom you can. The information is provided in the longer comment above is still relevant. The key file is `metro.config.js`.

I found two more semi-related issues. My config seems to mirror most examples:

Migrating an expo app to turbo: 
https://www.jumr.dev/blog/t3-turbo

a similar issue concerning expo-router:
https://github.com/expo/router/issues/786

**Comment by julienblin** [comment]
@nickvallee - this is because you are misguided.
The purpose of this issue is to create a project **template**, not to add an expo sample app in the monorepo. As I've told you, running Expo in this monorepo is going to introduce a ton of problems.

As mentioned [here](https://github.com/bonfhir/bonfhir/issues/146#issuecomment-1858463801), project templates are located in the `cli` packages, under the `template` folder.
They create new projects _outside_ of the monorepo. If you explore you'll find templates for Vite, Next.js, and AWS Lambda mainly.

This is what get executed when you run `npm create -y bonfhir@latest` anywhere on your terminal.

What we want is a new template that create an expo app, pre-configured with the new `@bonfhir/gluestack-ui` package.
It should be similar to the [Vite](https://github.com/bonfhir/bonfhir/blob/main/packages/cli/src/templates/vite.ts) or [Next](https://github.com/bonfhir/bonfhir/blob/main/packages/cli/src/templates/next.ts) templates.

**Comment by nickvallee** [comment]
@julienblin Understood! thank you for guiding me in the correct direction 👍
